{% set name = "pyspnego" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyspnego-{{ version }}.tar.gz
  sha256: 17dda4fbf725094c440e68709601c1575db83d9c844c9efedf0ad4dd1b72e5a0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - cryptography
    - ruamel.yaml
    - sspilib >=0.1.0  # [win]
  run_constrained:
    - python-gssapi >=1.6.0  # [not win]
    - python-krb5 >=0.3.0  # [not win]

test:
  imports:
    - spnego
    - spnego._ntlm_raw
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jborean93/pyspnego
  summary: Windows Negotiate Authentication Client and Server
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
    - krisevans
    - rzillman
